### ISSUE TITLE
Cannot upload workspace because of problem during metadata extraction

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#5]
Request:

```
curl -F "compendium=@/home/daniel/ownCloud/o2r-data/Korpus/public/workspace-rmd-data.zip;type=application/zip" -F content_type=workspace --cookie "connect.sid=s:ADOteuwd4fUZcGTBuc6cH7UaK0Czk7cd.Bb9x3m1vodnlEyvVZWH9vZeC4gxloqtBS1IsD9g7YZI" http://localhost/api/v1/compendium
```

Stacktrace:

```
loader_1          | 2019-05-23T07:23:56.037Z loader:steps [9EUG7] Input dir: /tmp/o2r/compendium/9EUG7 | Output dir: /tmp/o2r/compendium/9EUG7/.erc
loader_1          | 2019-05-23T07:23:56.037Z loader:steps [9EUG7] Created output dir: /tmp/o2r/compendium/9EUG7/.erc
loader_1          | 2019-05-23T07:23:56.038Z loader:steps [9EUG7] volume is configured, overwriting binds configuration (was [ '/tmp/o2r/compendium/9EUG7:/tmp/o2r/compendium/9EUG7', '/tmp/o2r/compendium/9EUG7/.erc:/tmp/o2r/compendium/9EUG7/.erc' ])
loader_1          | 2019-05-23T07:23:56.038Z loader:steps [9EUG7] Binds: [ 'o2rplatform_o2rstorage:/tmp/o2r/' ]
loader_1          | 2019-05-23T07:23:56.038Z loader:steps [9EUG7] Starting Docker container now with options and command:
loader_1          |     create_options: {"CpuShares":128,"Env":["O2R_LOADER=true"],"Memory":1073741824,"MemorySwap":2147483648,"User":"root","name":"meta_extract_9EUG7","HostConfig":{"Binds":["o2rplatform_o2rstorage:/tmp/o2r/"],"AutoRemove":true}}
loader_1          |     start_options: {}
loader_1          |     cmd: -debug extract --inputdir /tmp/o2r/compendium/9EUG7 --outputdir /tmp/o2r/compendium/9EUG7/.erc --metafiles --ercid 9EUG7 --basedir /tmp/o2r/compendium/9EUG7
loader_1          | 2019-05-23T07:23:56.041Z modem Sending: { path: '/containers/create?Hostname=&User=root&AttachStdin=false&AttachStdout=true&AttachStderr=true&Tty=true&OpenStdin=false&StdinOnce=false&Env=%5B%22O2R_LOADER%3Dtrue%22%5D&Cmd=%5B%22-debug%22%2C%22extract%22%2C%22--inputdir%22%2C%22%2Ftmp%2Fo2r%2Fcompendium%2F9EUG7%22%2C%22--outputdir%22%2C%22%2Ftmp%2Fo2r%2Fcompendium%2F9EUG7%2F.erc%22%2C%22--metafiles%22%2C%22--ercid%22%2C%229EUG7%22%2C%22--basedir%22%2C%22%2Ftmp%2Fo2r%2Fcompendium%2F9EUG7%22%5D&Image=o2rproject%2Fo2r-meta%3A9198450&Volumes=%7B%7D&VolumesFrom=%5B%5D&CpuShares=128&Memory=1073741824&MemorySwap=2147483648&name=meta_extract_9EUG7&HostConfig=%7B%22Binds%22%3A%5B%22o2rplatform_o2rstorage%3A%2Ftmp%2Fo2r%2F%22%5D%2C%22AutoRemove%22%3Atrue%7D',
loader_1          |   method: 'POST',
loader_1          |   headers: { 'Content-Type': 'application/json', 'Content-Length': 583 },
loader_1          |   key: undefined,
loader_1          |   cert: undefined,
loader_1          |   ca: undefined,
loader_1          |   socketPath: '/var/run/docker.sock' }
loader_1          | 2019-05-23T07:23:56.487Z modem Received: {"Id":"628154d9d3ecd416d9bd1757615d10d92627afcaad649d8770dd0e68e3139a9f","Warnings":null}
loader_1          | 
loader_1          | 2019-05-23T07:23:56.489Z modem Sending: { path: '/containers/628154d9d3ecd416d9bd1757615d10d92627afcaad649d8770dd0e68e3139a9f/attach?stream=true&stdout=true&stderr=true',
loader_1          |   method: 'POST',
loader_1          |   headers: { 'Content-Type': 'application/json', 'Content-Length': 43 },
loader_1          |   key: undefined,
loader_1          |   cert: undefined,
loader_1          |   ca: undefined,
loader_1          |   socketPath: '/var/run/docker.sock' }
loader_1          | 2019-05-23T07:23:56.503Z modem Sending: { path: '/containers/628154d9d3ecd416d9bd1757615d10d92627afcaad649d8770dd0e68e3139a9f/start',
loader_1          |   method: 'POST',
loader_1          |   headers: {},
loader_1          |   key: undefined,
loader_1          |   cert: undefined,
loader_1          |   ca: undefined,
loader_1          |   socketPath: '/var/run/docker.sock' }
loader_1          | 2019-05-23T07:23:58.516Z modem Received: 
loader_1          | 2019-05-23T07:23:58.536Z modem Sending: { path: '/containers/628154d9d3ecd416d9bd1757615d10d92627afcaad649d8770dd0e68e3139a9f/wait',
loader_1          |   method: 'POST',
loader_1          |   headers: {},
loader_1          |   key: undefined,
loader_1          |   cert: undefined,
loader_1          |   ca: undefined,
loader_1          |   socketPath: '/var/run/docker.sock' }
loader_1          | 2019-05-23T07:23:58.891Z loader:steps [9EUG7] [extract container] [o2rmeta] 20190523.072358 received arguments: {'debug': True, 'tool': 'extract', 'formats': False, 'inputdir': '/tmp/o2r/compendium/9EUG7', 'outputdir': '/tmp/o2r/compendium/9EUG7/.erc', 'outputtostdout': False, 'ercid': '9EUG7', 'basedir': '/tmp/o2r/compendium/9EUG7', 'modexml': False, 'stayoffline': False, 'metafiles': True, 'default_metadata_license': None}
loader_1          | [o2rmeta] 20190523.072358 launching extractor
loader_1          | 2019-05-23T07:23:58.892Z loader:steps [9EUG7] [extract container] [o2rmeta][debug: extract.metaextract @ start] 20190523.072358 Using CC-BY-4.0 as default license for metadata
loader_1          | 2019-05-23T07:23:58.893Z loader:steps [9EUG7] [extract container] [o2rmeta] 20190523.072358 directory </tmp/o2r/compendium/9EUG7/.erc> will be created during extraction...
loader_1          | 2019-05-23T07:23:58.894Z loader:steps [9EUG7] [extract container] [o2rmeta][error][debug: extract.metaextract @ start] 20190523.072358 ! error, input dir </tmp/o2r/compendium/9EUG7> does not exist
loader_1          | [o2rmeta][debug: extract.metaextract @ start] 20190523.072358 ! error, input dir </tmp/o2r/compendium/9EUG7> does not exist
loader_1          | 2019-05-23T07:23:59.900Z modem Received: {"Error":null,"StatusCode":1}
loader_1          | 
loader_1          | 2019-05-23T07:23:59.901Z loader:steps [9EUG7] container running: [object Object]
loader_1          | 2019-05-23T07:23:59.901Z loader:steps [9EUG7] Error during meta container run: { Error: null, StatusCode: 1 }
loader_1          | 2019-05-23T07:23:59.902Z modem Sending: { path: '/containers/628154d9d3ecd416d9bd1757615d10d92627afcaad649d8770dd0e68e3139a9f/logs?follow=true&stdout=true&stderr=true&timestamps=true',
loader_1          |   method: 'GET',
loader_1          |   headers: {},
loader_1          |   key: undefined,
loader_1          |   cert: undefined,
loader_1          |   ca: undefined,
loader_1          |   socketPath: '/var/run/docker.sock' }
loader_1          | 2019-05-23T07:23:59.923Z loader:directuploader [9EUG7] Rejection or unhandled failure during upload: Error: Received non-zero statuscode from container at docker.run (/loader/lib/steps.js:868:28) at /loader/node_modules/dockerode/lib/docker.js:1448:11 at /loader/node_modules/dockerode/lib/container.js:783:7 at Modem.buildPayload (/loader/node_modules/docker-modem/lib/modem.js:270:7) at IncomingMessage.<anonymous> (/loader/node_modules/docker-modem/lib/modem.js:229:14) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:139:11) at process._tickCallback (internal/process/next_tick.js:181:9)
loader_1          | 2019-05-23T07:23:59.926Z loader:directuploader [{ id: '9EUG7',
loader_1          |   user: '0000-0001-6225-344X',
loader_1          |   content: 'workspace',
loader_1          |   req: 
loader_1          |    IncomingMessage {
loader_1          |      _readableState: [Object],
loader_1          |      readable: false,
loader_1          |      domain: null,
loader_1          |      _events: [Object],
loader_1          |      _eventsCount: 1,
loader_1          |      _maxListeners: undefined,
loader_1          |      socket: [Object],
loader_1          |      connection: [Object],
loader_1          |      httpVersionMajor: 1,
loader_1          |      httpVersionMinor: 0,
loader_1          |      httpVersion: '1.0',
loader_1          |      complete: true,
loader_1          |      headers: [Object],
loader_1          |      rawHeaders: [Array],
loader_1          |      trailers: {},
loader_1          |      rawTrailers: [],
loader_1          |      aborted: false,
loader_1          |      upgrade: false,
loader_1          |      url: '/api/v1/compendium',
loader_1          |      method: 'POST',
loader_1          |      statusCode: null,
loader_1          |      statusMessage: null,
loader_1          |      client: [Object],
loader_1          |      _consuming: true,
loader_1          |      _dumped: false,
loader_1          |      next: [Function: next],
loader_1          |      baseUrl: '',
loader_1          |      originalUrl: '/api/v1/compendium',
loader_1          |      _parsedUrl: [Object],
loader_1          |      params: {},
loader_1          |      query: {},
loader_1          |      res: [Object],
loader_1          |      body: [Object],
loader_1          |      _parsedOriginalUrl: [Object],
loader_1          |      sessionStore: [Object],
loader_1          |      sessionID: 'ADOteuwd4fUZcGTBuc6cH7UaK0Czk7cd',
loader_1          |      session: [Object],
loader_1          |      _passport: [Object],
loader_1          |      user: [Object],
loader_1          |      route: [Object],
loader_1          |      read: [Function],
loader_1          |      file: [Object] },
loader_1          |   res: 
loader_1          |    ServerResponse {
loader_1          |      domain: null,
loader_1          |      _events: [Object],
loader_1          |      _eventsCount: 1,
loader_1          |      _maxListeners: undefined,
loader_1          |      output: [],
loader_1          |      outputEncodings: [],
loader_1          |      outputCallbacks: [],
loader_1          |      outputSize: 0,
loader_1          |      writable: true,
loader_1          |      _last: false,
loader_1          |      upgrading: false,
loader_1          |      chunkedEncoding: false,
loader_1          |      shouldKeepAlive: false,
loader_1          |      useChunkedEncodingByDefault: false,
loader_1          |      sendDate: true,
loader_1          |      _removedConnection: false,
loader_1          |      _removedContLen: false,
loader_1          |      _removedTE: false,
loader_1          |      _contentLength: null,
loader_1          |      _hasBody: true,
loader_1          |      _trailer: '',
loader_1          |      finished: false,
loader_1          |      _headerSent: false,
loader_1          |      socket: [Object],
loader_1          |      connection: [Object],
loader_1          |      _header: null,
loader_1          |      _onPendingData: [Function: bound updateOutgoingData],
loader_1          |      _sent100: false,
loader_1          |      _expect_continue: false,
loader_1          |      req: [Object],
loader_1          |      locals: {},
loader_1          |      writeHead: [Function: writeHead],
loader_1          |      end: [Function: end],
loader_1          |      [Symbol(outHeadersKey)]: [Object] },
loader_1          |   archive: '/tmp/o2r/incoming/9EUG7',
loader_1          |   compendium_path: '/tmp/o2r/compendium/9EUG7',
loader_1          |   textFiles: [ '/tmp/o2r/compendium/9EUG7/main.Rmd' ],
loader_1          |   isBag: false,
loader_1          |   bagValid: null,
loader_1          |   configurationFile: '/tmp/o2r/compendium/9EUG7/erc.yml' }] Passon object:
loader_1          | %s
loader_1          | 2019-05-23T07:23:59.929Z loader:ctrl:directupload Error during upload: Error: Received non-zero statuscode from container at docker.run (/loader/lib/steps.js:868:28) at /loader/node_modules/dockerode/lib/docker.js:1448:11 at /loader/node_modules/dockerode/lib/container.js:783:7 at Modem.buildPayload (/loader/node_modules/docker-modem/lib/modem.js:270:7) at IncomingMessage.<anonymous> (/loader/node_modules/docker-modem/lib/modem.js:229:14) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:139:11) at process._tickCallback (internal/process/next_tick.js:181:9)
webserver_1       | 172.20.0.1 - - [23/May/2019:07:23:59 +0000] "POST /api/v1/compendium HTTP/1.1" 500 50 "-" "curl/7.58.0"
loader_1          | 2019-05-23T07:23:59.948Z loader:steps [9EUG7] Error getting container logs after non-zero status code
```

**Comment by nuest** [comment]
Tried to check if the Docker socket is available within the container:

```
$ docker-compose run --name bugfixing --no-deps loader /bin/sh
# pwd
/loader
# curl --unix-socket /var/run/docker.sock http/info
{"ID":"WTH7:5FJR:TWR3:ZXIM:JZZP:5NKF:BUPJ:5OC2:VYPX:QOPP:SPT7:STJB","Containers":21,"ContainersRunning":18,"ContainersPaused":0,"ContainersStopped":3,"Images":1003,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","true"]],"SystemStatus":null,"Plugins":{"Volume":["local"],"Network":["bridge","host","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"KernelMemory":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":217,"OomKillDisable":true,"NGoroutines":276,"SystemTime":"2019-05-23T14:48:29.762292055+02:00","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","NEventsListener":1,"KernelVersion":"4.15.0-50-generic","OperatingSystem":"Ubuntu 18.04.2 LTS","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true},"gin-nuest:5000":{"Name":"gin-nuest:5000","Mirrors":[],"Secure":false,"Official":false},"localhost:5000":{"Name":"localhost:5000","Mirrors":[],"Secure":false,"Official":false}},"Mirrors":[]},"NCPU":4,"MemTotal":12277575680,"GenericResources":null,"DockerRootDir":"/var/lib/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"gin-nuest","Labels":[],"ExperimentalBuild":false,"ServerVersion":"18.09.6","ClusterStore":"","ClusterAdvertise":"","Runtimes":{"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"bb71b10fd8f58240ca47fbb579b9d1028eea7c84","Expected":"bb71b10fd8f58240ca47fbb579b9d1028eea7c84"},"RuncCommit":{"ID":"2b18fe1d885ee5083ef9f0838fee39b62d653e30","Expected":"2b18fe1d885ee5083ef9f0838fee39b62d653e30"},"InitCommit":{"ID":"fec3683","Expected":"fec3683"},"SecurityOptions":["name=apparmor","name=seccomp,profile=default"],"ProductLicense":"Community Engine","Warnings":null}
```

It is! And so is the directory:

```
# pwd
/tmp/o2r/compendium
# cd 9EUG7
# ls
data.csv  display.html  main.Rmd
```

**The name of the volume changed.** On the host:

```
daniel@gin-nuest:~/git/o2r/o2r-UI$ docker volume ls
DRIVER              VOLUME NAME
local               0a89f04fc787207c69ae8a5a7951ed4e93bacad1adcacd1914a909aa4c36f13e
local               0ac7eaa655de8346eda46887b4eb8d302e8911524ce997668c24906c7e4bda5c
local               0d1cad68e4399272cad412dbc52056495bceb042932bca3cf999ee6bc3e53d17
[...]
local               ffd5e67a1f85d01f1833cadb72ac0072c4c9ca85d3638f11f437297ba6b0075c
local               o2rplatform_o2rstorage
local               referenceimplementation_o2rvol
local               sos4R
local               ui_o2rstorage
daniel@gin-nuest:~/git/o2r/o2r-UI$ 
```

**Comment by nuest** [comment]
```
daniel@gin-nuest:~/git/o2r/o2r-UI$ curl -F "compendium=@/home/daniel/ownCloud/o2r-data/Korpus/public/workspace-rmd-data.zip;type=application/zip" -F content_type=workspace --cookie "connect.sid=s:b8
cckPYgeYEaFHAVBE5C5z-uJzvcb50M.TTrfR03QH130df4F9FOzvV7jP1I9nUUqpyclftPSVl0" http://localhost/api/v1/compendium
{"id":"3aFyQ"}daniel@gin-nuest:~/git/o2r
curl: try 'curl --help' or 'curl --manual' for more information
daniel@gin-nuest:~/git/o2r/o2r-UI$ curl http://localhost/api/v1/compendium/3aFyQ
daniel@gin-nuest:~/git/o2r/o2r-UI$ "}daniel@gin-nuest:~/git/o2r/o2r-UI$ curl --cookie "connect.sid=s:b8cckPYgeYEaFHAVBE5C5z-uJzvcb50M.TTrfR03QH130df4F9FOzvV7jP1I9nUUqpyclftPSVl0" http://localhost/ap
i/v1/compendium/3aFyQ
> 
> ^C
daniel@gin-nuest:~/git/o2r/o2r-UI$ ^C
daniel@gin-nuest:~/git/o2r/o2r-UI$ curl --cookie "connect.sid=s:b8cckPYgeYEaFHAVBE5C5z-uJzvcb50M.TTrfR03QH130df4F9FOzvV7jP1I9nUUqpyclftPSVl0" http://localhost/api/v1/compendium/3aFyQ
{"id":"3aFyQ","metadata":{"raw":{"access_right":"open","author":[{"affiliation":"o2r team","name":"Daniel Nüst","orcid":"0000-0002-0024-5046"}],"bagit":{"bagittxt_files":[]},"codefiles":["main.Rmd"]
,"communities":[{"identifier":"o2r"}],"depends":[],"description":"Capacity of container ships in seaborne trade of the world container ship fleet.\n","displayfile":"display.html","displayfile_candid
ates":["display.html"],"file":{"filename":null,"filepath":null,"mimetype":null},"generatedBy":"o2r-meta metaextract.py","identifier":{"doi":"10.5555/666655554444","doiurl":"https://doi.org/10.5555/6
66655554444","reserveddoi":null},"inputfiles":["data.csv"],"interaction":[],"keywords":["container","ship","trade","statistic"],"license":{"code":null,"data":null,"metadata":"CC-BY-4.0","text":null},"mainfile":"main.Rmd","mainfile_candidates":["main.Rmd"],"ncdf":{"ncdf_files":[]},"paperLanguage":[],"provenance":[],"publicationDate":"2019-05-23","publication_type":"other","r_comment":[],"r_input":[{"feature":"data input","line":2,"text":"data.csv"}],"r_output":[{"feature":"result","line":3,"text":"plot"}],"rdata":{"rdata_files":[]},"recordDateCreated":null,"researchHypotheses":[],"researchQuestions":[],"softwarePaperCitation":null,"spatial":{"files":[],"union":{"bbox":[[181,181],[-181,181],[-181,-181],[181,-181]]}},"temporal":{"begin":"2017-05-23T00:00:00","end":"2017-05-23T00:00:00"},"title":"Capacity of container ships in seaborne trade from 1980 to 2016 (in million dwt)*","upload_type":"publication","version":null},"o2r":{"access_right":"open","codefiles":["main.Rmd"],"communities":[{"identifier":"o2r"}],"creators":[{"affiliation":"o2r team","name":"Daniel Nüst","orcid":"0000-0002-0024-5046"}],"depends":[],"description":"Capacity of container ships in seaborne trade of the world container ship fleet.\n","displayfile":"display.html","displayfile_candidates":["display.html"],"identifier":{"doi":"10.5555/666655554444","doiurl":"https://doi.org/10.5555/666655554444","reserveddoi":null},"inputfiles":["data.csv"],"interaction":[],"keywords":["container","ship","trade","statistic"],"license":{"code":null,"data":null,"metadata":"CC-BY-4.0","text":null},"mainfile":"main.Rmd","mainfile_candidates":["main.Rmd"],"paperLanguage":[],"publication_date":"2019-05-23","publication_type":"other","spatial":{"files":[],"union":{"bbox":[[181,181],[-181,181],[-181,-181],[181,-181]]}},"temporal":{"begin":"2017-05-23T00:00:00","end":"2017-05-23T00:00:00"},"title":"Capacity of container ships in seaborne trade from 1980 to 2016 (in million dwt)*","upload_type":"publication"}},"created":"2019-05-23T14:34:53.763Z","user":"0000-0001-6225-344X","bag":false,"compendium":false,"substituted":false,"files":{"path":"/api/v1/compendium/3aFyQ/data","name":"3aFyQ","children":[{"path":"/api/v1/compendium/3aFyQ/data/.erc","name":".erc","children":[{"path":"/api/v1/compendium/3aFyQ/data/.erc/erc_spec.pdf","name":"erc_spec.pdf","size":301867,"extension":".pdf","type":"application/pdf"},{"path":"/api/v1/compendium/3aFyQ/data/.erc/metadata_o2r_1.json","name":"metadata_o2r_1.json","size":1871,"extension":".json","type":"application/json"},{"path":"/api/v1/compendium/3aFyQ/data/.erc/metadata_raw.json","name":"metadata_raw.json","size":2609,"extension":".json","type":"application/json"},{"path":"/api/v1/compendium/3aFyQ/data/.erc/package_slip.json","name":"package_slip.json","size":409,"extension":".json","type":"application/json"}],"size":306756,"type":"directory"},{"path":"/api/v1/compendium/3aFyQ/data/data.csv","name":"data.csv","size":122,"extension":".csv","type":"text/csv"},{"path":"/api/v1/compendium/3aFyQ/data/display.html","name":"display.html","size":651313,"extension":".html","type":"text/html"},{"path":"/api/v1/compendium/3aFyQ/data/main.Rmd","name":"main.Rmd","size":1117,"extension":".rmd"}],"size":959308,"type":"directory"},"candidate":true}
```
